import { ComponentPresets, ComponentPresetOptions } from '../../interfaces';

export default {
  default: {
    name: 'Sidebar Component',
    props: {
      component: {
        tag: 'ion-button',
        encapsulation: 'shadow',
        readme:
          '# ion-button\r\n\r\nButtons provide a clickable element, which can be used in forms, or anywhere that needs simple, standard button functionality. They may display text, icons, or both. Buttons can be styled with several attributes to look a specific way.\r\n\r\n## Expand\r\n\r\nThis attribute lets you specify how wide the button should be. By default, buttons are inline blocks, but setting this attribute will change the button to a full-width block element.\r\n\r\n| Value          | Details                                                                      |\r\n|----------------|------------------------------------------------------------------------------|\r\n| `block`        | Full-width button with rounded corners.                                      |\r\n| `full`         | Full-width button with square corners and no border on the left or right.    |\r\n\r\n## Fill\r\n\r\nThis attributes determines the background and border color of the button. By default, buttons have a solid background unless the button is inside of a toolbar, in which case it has a transparent background.\r\n\r\n| Value          | Details                                                                      |\r\n|----------------|------------------------------------------------------------------------------|\r\n| `clear`        | Button with a transparent background that resembles a flat button.           |\r\n| `outline`      | Button with a transparent background and a visible border.                   |\r\n| `solid`        | Button with a filled background. Useful for buttons in a toolbar.            |\r\n\r\n## Size\r\n\r\nThis attribute specifies the size of the button. Setting this attribute will change the height and padding of a button.\r\n\r\n| Value          | Details                                                                      |\r\n|----------------|------------------------------------------------------------------------------|\r\n| `small`        | Button with less height and padding. Default for buttons in an item.         |\r\n| `default`      | Button with the default height and padding. Useful for buttons in an item.   |\r\n| `large`        | Button with more height and padding.                                         |\r\n\r\n\r',
        docs: 'Buttons provide a clickable element, which can be used in forms, or anywhere that needs simple, standard button functionality. They may display text, icons, or both. Buttons can be styled with several attributes to look a specific way.',
        docsTags: [
          {
            name: 'slot',
            text: '- Content is placed between the named slots if provided without a slot.',
          },
          {
            name: 'slot',
            text: 'icon-only - Should be used on an icon in a button that has no text.',
          },
          {
            name: 'slot',
            text: 'start - Content is placed to the left of the button text in LTR, and to the right in RTL.',
          },
          {
            name: 'slot',
            text: 'end - Content is placed to the right of the button text in LTR, and to the left in RTL.',
          },
        ],
        usage: {
          angular:
            '\r\n```html\r\n<!-- Default -->\r\n<ion-button>Default</ion-button>\r\n\r\n<!-- Anchor -->\r\n<ion-button href="#">Anchor</ion-button>\r\n\r\n<!-- Colors -->\r\n<ion-button color="primary">Primary</ion-button>\r\n<ion-button color="secondary">Secondary</ion-button>\r\n<ion-button color="tertiary">Tertiary</ion-button>\r\n<ion-button color="success">Success</ion-button>\r\n<ion-button color="warning">Warning</ion-button>\r\n<ion-button color="danger">Danger</ion-button>\r\n<ion-button color="light">Light</ion-button>\r\n<ion-button color="medium">Medium</ion-button>\r\n<ion-button color="dark">Dark</ion-button>\r\n\r\n<!-- Expand -->\r\n<ion-button expand="full">Full Button</ion-button>\r\n<ion-button expand="block">Block Button</ion-button>\r\n\r\n<!-- Round -->\r\n<ion-button shape="round">Round Button</ion-button>\r\n\r\n<!-- Fill -->\r\n<ion-button expand="full" fill="outline">Outline + Full</ion-button>\r\n<ion-button expand="block" fill="outline">Outline + Block</ion-button>\r\n<ion-button shape="round" fill="outline">Outline + Round</ion-button>\r\n\r\n<!-- Icons -->\r\n<ion-button>\r\n  <ion-icon slot="start" name="star"></ion-icon>\r\n  Left Icon\r\n</ion-button>\r\n\r\n<ion-button>\r\n  Right Icon\r\n  <ion-icon slot="end" name="star"></ion-icon>\r\n</ion-button>\r\n\r\n<ion-button>\r\n  <ion-icon slot="icon-only" name="star"></ion-icon>\r\n</ion-button>\r\n\r\n<!-- Sizes -->\r\n<ion-button size="large">Large</ion-button>\r\n<ion-button>Default</ion-button>\r\n<ion-button size="small">Small</ion-button>\r\n```\r\n',
          javascript:
            '\r\n```html\r\n<!-- Default -->\r\n<ion-button>Default</ion-button>\r\n\r\n<!-- Anchor -->\r\n<ion-button href="#">Anchor</ion-button>\r\n\r\n<!-- Colors -->\r\n<ion-button color="primary">Primary</ion-button>\r\n<ion-button color="secondary">Secondary</ion-button>\r\n<ion-button color="tertiary">Tertiary</ion-button>\r\n<ion-button color="success">Success</ion-button>\r\n<ion-button color="warning">Warning</ion-button>\r\n<ion-button color="danger">Danger</ion-button>\r\n<ion-button color="light">Light</ion-button>\r\n<ion-button color="medium">Medium</ion-button>\r\n<ion-button color="dark">Dark</ion-button>\r\n\r\n<!-- Expand -->\r\n<ion-button expand="full">Full Button</ion-button>\r\n<ion-button expand="block">Block Button</ion-button>\r\n\r\n<!-- Round -->\r\n<ion-button shape="round">Round Button</ion-button>\r\n\r\n<!-- Fill -->\r\n<ion-button expand="full" fill="outline">Outline + Full</ion-button>\r\n<ion-button expand="block" fill="outline">Outline + Block</ion-button>\r\n<ion-button shape="round" fill="outline">Outline + Round</ion-button>\r\n\r\n<!-- Icons -->\r\n<ion-button>\r\n  <ion-icon slot="start" name="star"></ion-icon>\r\n  Left Icon\r\n</ion-button>\r\n\r\n<ion-button>\r\n  Right Icon\r\n  <ion-icon slot="end" name="star"></ion-icon>\r\n</ion-button>\r\n\r\n<ion-button>\r\n  <ion-icon slot="icon-only" name="star"></ion-icon>\r\n</ion-button>\r\n\r\n<!-- Sizes -->\r\n<ion-button size="large">Large</ion-button>\r\n<ion-button>Default</ion-button>\r\n<ion-button size="small">Small</ion-button>\r\n```\r\n',
          react:
            '```tsx\r\nimport React from \'react\';\r\n\r\nimport { IonButton, IonIcon } from \'@ionic/react\';\r\n\r\nconst Example: React.SFC<{}> = () => (\r\n  <>\r\n    {/*-- Default --*/}\r\n    <IonButton>Default</IonButton>\r\n\r\n    {/*-- Anchor --*/}\r\n    <IonButton href="#">Anchor</IonButton>\r\n\r\n    {/*-- Colors --*/}\r\n    <IonButton color="primary">Primary</IonButton>\r\n    <IonButton color="secondary">Secondary</IonButton>\r\n    <IonButton color="tertiary">Tertiary</IonButton>\r\n    <IonButton color="success">Success</IonButton>\r\n    <IonButton color="warning">Warning</IonButton>\r\n    <IonButton color="danger">Danger</IonButton>\r\n    <IonButton color="light">Light</IonButton>\r\n    <IonButton color="medium">Medium</IonButton>\r\n    <IonButton color="dark">Dark</IonButton>\r\n\r\n    {/*-- Expand --*/}\r\n    <IonButton expand="full">Full Button</IonButton>\r\n    <IonButton expand="block">Block Button</IonButton>\r\n\r\n    {/*-- Round --*/}\r\n    <IonButton shape="round">Round Button</IonButton>\r\n\r\n    {/*-- Fill --*/}\r\n    <IonButton expand="full" fill="outline">Outline + Full</IonButton>\r\n    <IonButton expand="block" fill="outline">Outline + Block</IonButton>\r\n    <IonButton shape="round" fill="outline">Outline + Round</IonButton>\r\n\r\n    {/*-- Icons --*/}\r\n    <IonButton>\r\n      <IonIcon slot="start" name="star" />\r\n      Left Icon\r\n    </IonButton>\r\n\r\n    <IonButton>\r\n      Right Icon\r\n      <IonIcon slot="end" name="star" />\r\n    </IonButton>\r\n\r\n    <IonButton>\r\n      <IonIcon slot="icon-only" name="star" />\r\n    </IonButton>\r\n\r\n    {/*-- Sizes --*/}\r\n    <IonButton size="large">Large</IonButton>\r\n    <IonButton>Default</IonButton>\r\n    <IonButton size="small">Small</IonButton>\r\n  </>\r\n);\r\n\r\nexport default Example;\r\n```\r\n',
          vue: '```html\r\n<template>\r\n  <!-- Default -->\r\n  <ion-button>Default</ion-button>\r\n\r\n  <!-- Anchor -->\r\n  <ion-button href="#">Anchor</ion-button>\r\n\r\n  <!-- Colors -->\r\n  <ion-button color="primary">Primary</ion-button>\r\n  <ion-button color="secondary">Secondary</ion-button>\r\n  <ion-button color="tertiary">Tertiary</ion-button>\r\n  <ion-button color="success">Success</ion-button>\r\n  <ion-button color="warning">Warning</ion-button>\r\n  <ion-button color="danger">Danger</ion-button>\r\n  <ion-button color="light">Light</ion-button>\r\n  <ion-button color="medium">Medium</ion-button>\r\n  <ion-button color="dark">Dark</ion-button>\r\n\r\n  <!-- Expand -->\r\n  <ion-button expand="full">Full Button</ion-button>\r\n  <ion-button expand="block">Block Button</ion-button>\r\n\r\n  <!-- Round -->\r\n  <ion-button shape="round">Round Button</ion-button>\r\n\r\n  <!-- Fill -->\r\n  <ion-button expand="full" fill="outline">Outline + Full</ion-button>\r\n  <ion-button expand="block" fill="outline">Outline + Block</ion-button>\r\n  <ion-button shape="round" fill="outline">Outline + Round</ion-button>\r\n\r\n  <!-- Icons -->\r\n  <ion-button>\r\n    <ion-icon slot="start" name="star"></ion-icon>\r\n    Left Icon\r\n  </ion-button>\r\n\r\n  <ion-button>\r\n    Right Icon\r\n    <ion-icon slot="end" name="star"></ion-icon>\r\n  </ion-button>\r\n\r\n  <ion-button>\r\n    <ion-icon slot="icon-only" name="star"></ion-icon>\r\n  </ion-button>\r\n\r\n  <!-- Sizes -->\r\n  <ion-button size="large">Large</ion-button>\r\n  <ion-button>Default</ion-button>\r\n  <ion-button size="small">Small</ion-button>\r\n</template>\r\n```\r\n',
        },
        props: [
          {
            name: 'buttonType',
            type: 'string',
            mutable: true,
            attr: 'button-type',
            reflectToAttr: false,
            docs: 'The type of button.',
            docsTags: [],
            default: "'button'",
            optional: false,
            required: false,
          },
          {
            name: 'color',
            type: 'string | undefined',
            mutable: false,
            attr: 'color',
            reflectToAttr: false,
            docs: 'The color to use from your application\'s color palette.\r\nDefault options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`.\r\nFor more information on colors, see [theming](/docs/theming/basics).',
            docsTags: [],
            optional: true,
            required: false,
          },
          {
            name: 'disabled',
            type: 'boolean',
            mutable: false,
            attr: 'disabled',
            reflectToAttr: true,
            docs: 'If `true`, the user cannot interact with the button.',
            docsTags: [],
            default: 'false',
            optional: false,
            required: false,
          },
          {
            name: 'expand',
            type: '"block" | "full" | undefined',
            mutable: false,
            attr: 'expand',
            reflectToAttr: true,
            docs: 'Set to `"block"` for a full-width button or to `"full"` for a full-width button\r\nwithout left and right borders.',
            docsTags: [],
            optional: true,
            required: false,
          },
          {
            name: 'fill',
            type: '"clear" | "default" | "outline" | "solid" | undefined',
            mutable: true,
            attr: 'fill',
            reflectToAttr: true,
            docs: 'Set to `"clear"` for a transparent button, to `"outline"` for a transparent\r\nbutton with a border, or to `"solid"`. The default style is `"solid"` except inside of\r\na toolbar, where the default is `"clear"`.',
            docsTags: [],
            optional: true,
            required: false,
          },
          {
            name: 'href',
            type: 'string | undefined',
            mutable: false,
            attr: 'href',
            reflectToAttr: false,
            docs: 'Contains a URL or a URL fragment that the hyperlink points to.\r\nIf this property is set, an anchor tag will be rendered.',
            docsTags: [],
            optional: true,
            required: false,
          },
          {
            name: 'mode',
            type: '"ios" | "md"',
            mutable: false,
            attr: 'mode',
            reflectToAttr: false,
            docs: 'The mode determines which platform styles to use.',
            docsTags: [],
            optional: false,
            required: false,
          },
          {
            name: 'routerDirection',
            type: '"back" | "forward" | "root"',
            mutable: false,
            attr: 'router-direction',
            reflectToAttr: false,
            docs: 'When using a router, it specifies the transition direction when navigating to\r\nanother page using `href`.',
            docsTags: [],
            default: "'forward'",
            optional: false,
            required: false,
          },
          {
            name: 'shape',
            type: '"round" | undefined',
            mutable: false,
            attr: 'shape',
            reflectToAttr: true,
            docs: 'The button shape.',
            docsTags: [],
            optional: true,
            required: false,
          },
          {
            name: 'size',
            type: '"default" | "large" | "small" | undefined',
            mutable: false,
            attr: 'size',
            reflectToAttr: true,
            docs: 'The button size.',
            docsTags: [],
            optional: true,
            required: false,
          },
          {
            name: 'strong',
            type: 'boolean',
            mutable: false,
            attr: 'strong',
            reflectToAttr: false,
            docs: 'If `true`, activates a button with a heavier font weight.',
            docsTags: [],
            default: 'false',
            optional: false,
            required: false,
          },
          {
            name: 'type',
            type: '"button" | "reset" | "submit"',
            mutable: false,
            attr: 'type',
            reflectToAttr: false,
            docs: 'The type of the button.',
            docsTags: [],
            default: "'button'",
            optional: false,
            required: false,
          },
        ],
        methods: [],
        events: [
          {
            event: 'ionBlur',
            detail: 'void',
            bubbles: true,
            cancelable: true,
            composed: true,
            docs: 'Emitted when the button loses focus.',
            docsTags: [],
          },
          {
            event: 'ionFocus',
            detail: 'void',
            bubbles: true,
            cancelable: true,
            composed: true,
            docs: 'Emitted when the button has focus.',
            docsTags: [],
          },
        ],
        styles: [
          {
            name: '--background',
            annotation: 'prop',
            docs: 'Background of the button',
          },
          {
            name: '--background-activated',
            annotation: 'prop',
            docs: 'Background of the button when activated',
          },
          {
            name: '--background-focused',
            annotation: 'prop',
            docs: 'Background of the button when focused',
          },
          {
            name: '--border-color',
            annotation: 'prop',
            docs: 'Border color of the button',
          },
          {
            name: '--border-radius',
            annotation: 'prop',
            docs: 'Border radius of the button',
          },
          {
            name: '--border-style',
            annotation: 'prop',
            docs: 'Border style of the button',
          },
          {
            name: '--border-width',
            annotation: 'prop',
            docs: 'Border width of the button',
          },
          {
            name: '--box-shadow',
            annotation: 'prop',
            docs: 'Box shadow of the button',
          },
          {
            name: '--color',
            annotation: 'prop',
            docs: 'Text color of the button',
          },
          {
            name: '--color-activated',
            annotation: 'prop',
            docs: 'Text color of the button when activated',
          },
          {
            name: '--color-focused',
            annotation: 'prop',
            docs: 'Text color of the button when focused',
          },
          { name: '--opacity', annotation: 'prop', docs: 'Opacity of the button' },
          {
            name: '--padding-bottom',
            annotation: 'prop',
            docs: 'Padding bottom of the button',
          },
          {
            name: '--padding-end',
            annotation: 'prop',
            docs: 'Padding end of the button',
          },
          {
            name: '--padding-start',
            annotation: 'prop',
            docs: 'Padding start of the button',
          },
          {
            name: '--padding-top',
            annotation: 'prop',
            docs: 'Padding top of the button',
          },
          {
            name: '--ripple-color',
            annotation: 'prop',
            docs: 'Color of the button ripple effect',
          },
          {
            name: '--transition',
            annotation: 'prop',
            docs: 'Transition of the button',
          },
        ],
        slots: [
          {
            name: '',
            docs: 'Content is placed between the named slots if provided without a slot.',
          },
          {
            name: 'end',
            docs: 'Content is placed to the right of the button text in LTR, and to the left in RTL.',
          },
          {
            name: 'icon-only',
            docs: 'Should be used on an icon in a button that has no text.',
          },
          {
            name: 'start',
            docs: 'Content is placed to the left of the button text in LTR, and to the right in RTL.',
          },
        ],
      } as ComponentPresetOptions,
    },
  },
} as ComponentPresets;
